### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/tnf-ant-design-pro#1]
# 现有页面

## 登录页面

![image](https://github.com/user-attachments/assets/e3c5025c-929c-43f1-b95a-fbfc70916595)

## 欢迎页面

![image](https://github.com/user-attachments/assets/072f9db0-efb3-42d0-8354-fa7491cc5baa)

## 管理页面

![image](https://github.com/user-attachments/assets/eb15534d-1a88-4ce6-ad32-30b07b8c58b5)

## 表格页面

![image](https://github.com/user-attachments/assets/8ad6a8ca-62e1-420d-aea7-acb763d9e956)

# 区块

- [x] AccountCenter
- [x] FormStepForm
- [x] UserRegister
- [x] AccountSettings
- [x] UserRegisterResult
- [x] ListBasicList
- [x] DashboardAnalysis
- [x] ListCardList
- [x] DashboardMonitor
- [x] ListSearch
- [x] DashboardWorkplace
- [x] ListSearchApplications
- [x] EditorFlow
- [x] ListSearchArticles
- [x] EditorKoni
- [x] ListSearchProjects
- [x] EditorMind
- [x] ListTableList
- [x] EmptyPage
- [x] ProfileAdvanced
- [x] Exception403
- [x] ProfileBasic
- [x] Exception404
- [x] Exception500
- [x] FormAdvancedForm
- [x] ResultFail
- [x] FormBasicForm
- [x] ResultSuccess

# 功能

- [ ] 权限 https://github.com/umijs/tnf-ant-design-pro/issues/13
- [ ] 全局数据流
- [ ] 国际化
- [x] 用 fetch 替代 axios
- [ ] 其他（搜索 FIXME）
